version: '3.4'

services:
  vibe.virtualscooter:
    image: ${DOCKER_REGISTRY-}vibevirtualscooter
    build:
      context: .
      dockerfile: Vibe.VirtualScooter/Dockerfile
    environment:
        ASPNETCORE_URLS: "https://+;http://+"
        ASPNETCORE_HTTPS_PORT: "8001"
        ASPNETCORE_ENVIRONMENT: Development
    volumes:
    - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
    - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/