version: "3"
networks:
    deploy-guide-dev:
        driver: bridge

services:
    app:
        container_name: deploy-gide
        build:
            context: .
            dockerfile: ./Vibe.BackOffice/Vibe.BackOffice.Server/Dockerfile
        ports:
            - "8080:80"
        environment:
             - ASPNETCORE_HTTPS_PORTS=8081
             - ASPNETCORE_HTTP_PORTS=8080
             - ASPNETCORE_URLS=http://+:80
             - ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.AspNetCore.SpaProxy
        networks:
            - deploy-guide-dev
        depends_on: 
            - postgres_db
            - realtimechat.redis
    realtimechat.redis:
        image: redis
        restart: always
        networks:
            - deploy-guide-dev
        ports:
          - "6379:6379"    
    postgres_db:
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: vibe
        ports:
            - "5432:5432"
        networks:
            - deploy-guide-dev
        volumes:
            -  postgres-data:/var/lib/postgresql/data
            - ./db/:/docker-entrypoint-initdb.d
volumes:
    postgres-data: 